name: 🚀 Carven Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # 👈 permite execução manual

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: ⚙️ Instalar k6
        run: |
          sudo apt update
          sudo apt install -y gnupg software-properties-common
          sudo gpg -k
          sudo gpg --no-default-keyring --keyring /usr/share/keyrings/k6-archive-keyring.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 33A3E1C2
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt update
          sudo apt install k6

      - name: 🧪 Smoke Test
        run: k6 run tests/smoke/home.smoke.test.js

      - name: 📊 Load Test
        run: k6 run tests/load/home.load.test.js

      - name: 🔥 Stress Test
        run: k6 run tests/stress/home.stress.test.js