name: CI/CD - K6 Pipeline

on:
  push:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  ci:
    name: CI - Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install k6
        run: |
          sudo apt update
          sudo apt install -y k6

      - name: Run Performance Tests
        run: k6 run script.js

  cd:
    name: CD - Deploy Manual/Controlled
    needs: ci
    runs-on: ubuntu-latest
    if: success()

    environment:
      name: production
      url: https://seu-app.com

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Step
        run: echo "Deploy liberado (substituir por AWS/Vercel/Docker)"