name: 🚀 Carven Performance Tests

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:  # execução manual

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: ⚙️ Instalar k6
        run: |
          sudo apt update
          sudo apt install -y gnupg ca-certificates curl

          curl -fsSL https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6.gpg

          echo "deb [signed-by=/usr/share/keyrings/k6.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list

          sudo apt update
          sudo apt install -y k6

          k6 version

      - name: 🧪 Smoke Test
        run: k6 run tests/smoke/home.smoke.test.js

      - name: 📊 Load Test
        run: k6 run tests/load/home.load.test.js

      - name: 🔥 Stress Test
        run: k6 run tests/stress/home.stress.test.js

      - name: ⚡ Spike Test
        run: k6 run tests/spike/home.spike.test.js